---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dynatrace-operator
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: "oci://public.ecr.aws/dynatrace/dynatrace-operator"
  interval: 10m
  ref:
    tag: "1.6.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dynatrace-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: dynatrace-operator
      sourceRef:
        kind: OCIRepository
        name: dynatrace-operator
        namespace: ${workspaceNamespace}
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: dynatrace-operator
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: dynatrace-operator-1.6.1-mdr-defaults