---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: acme-issuers
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ./charts/acme-issuers
      sourceRef:
        kind: GitRepository
        name: mdr-catalog-applications
        namespace: ${workspaceNamespace}
      version: 0.3.0
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: acme-issuers
  targetNamespace: ${releaseNamespace}
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: acme-issuers-0.3.0-mdr-defaults