---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-cd-8.0.12-mdr-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    configs:
      params:
        # So we can use Traefik TLS termination
        server.insecure: true
      # So applications have a health check and can therefore be included in sync waves
      # See https://argo-cd.readthedocs.io/en/stable/operator-manual/health/
      cm:
        resource.customizations.health.argoproj.io_Application: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs
        statusbadge.enabled: true  

    # Metrics support
    controller:
      metrics:
        enabled: true
    applicationSet:
      metrics:
        enabled: true 
    dex:
      metrics:
        enabled: true
    redis:
      metrics:
        enabled: true
    server:
      metrics:
        enabled: true
    repoServer:
      metrics:
        enabled: true
    notifications:
      metrics:
        enabled: true

