---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: "${helmMirrorURL:=https://charts.gitlab.io}"
  interval: 10m
  timeout: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: ${workspaceNamespace}
      version: 9.0.2
  install:
    remediation:
      retries: 30
    timeout: 10m
  interval: 15s
  releaseName: gitlab
  targetNamespace: ${releaseNamespace}
  upgrade:
    timeout: 20m
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: gitlab-9.0.2-mdr-defaults